In [1]:
import torch
import numpy as np

In [6]:
a = torch.FloatTensor(3,2)
a.dtype

torch.float32

In [14]:
a = torch.Tensor(3,2) # New way
a.dtype

torch.float32

In [15]:
# (3,2) tensor = 3 rows, 2 columns
print(a)

tensor([[ 0.0000e+00, -8.5899e+09],
        [-7.1565e+22, -8.5920e+09],
        [-7.1426e+22,  2.0005e+00]])


In [16]:
b = torch.FloatTensor([[1,2,3],[3,2,1]])
print(b)
print(b.dtype)

tensor([[1., 2., 3.],
        [3., 2., 1.]])
torch.float32


In [18]:
b = torch.Tensor([[1,2,3],[3,2,1]])
print(b)
print(b.dtype)

tensor([[1., 2., 3.],
        [3., 2., 1.]])
torch.float32


In [23]:
n = np.zeros((3,2))
print(n)
b = torch.tensor(n)
print(b)
print(b.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
torch.float64


In [25]:
b = torch.zeros(3,2)
print(b)
print(b.dtype)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
torch.float32


In [28]:
n = np.zeros((3,2)).astype(np.float32)
b = torch.tensor(n)
print(b)
print(b.dtype)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
torch.float32


In [29]:
a = torch.tensor([1,2,3])
print(a)
print(a.dtype)

tensor([1, 2, 3])
torch.int64


In [31]:
print(a.sum())
print(a.sum().item())

tensor(6)
6


In [36]:
v1 = torch.tensor([1.0, 1.0], requires_grad=True)
v2 = torch.tensor([2.0, 2.0])
print(f'v1: {v1}\n')
print(f'v2: {v2}\n')
v_sum = v1 + v2
v_res = (v_sum*2).sum()
print(f'Sum: {v_sum}\n')
print(f'Res: {v_res}\n')
print(f'Is v1 constructed by user? {v1.is_leaf}\n')
print(f'Is v_sum constructed by user? {v_sum.is_leaf}\n')

# Calculating gradients of graph
v_res.backward()
print(f'Gradient of v1: {v1.grad}')

v1: tensor([1., 1.], requires_grad=True)

v2: tensor([2., 2.])

Sum: tensor([3., 3.], grad_fn=<AddBackward0>)

Res: 12.0

Is v1 constructed by user? True

Is v_sum constructed by user? False

Gradient of v1: tensor([2., 2.])


By calling ```backward``` function, we asked PyTorch to calculate the numerical derivative of the ```v_res``` variable, with respect to any variable that our graph has. 

*What influence do small changes to the ```v_res``` variable have on the rest of the graph?* 

Keep in note, that PyTorch calculates gradients only for leaf tensors with ```requires_grad=True```